<div class="login_box">
 <div class="user_cont">
<div id="cperror" style="color:red;height:20px;font-size:14px;width:500px;"><?php  
echo $this->message['updatepassword'];?></div>
<?php 

		$this->form->setAction($this->url());
		echo $this->form->getDecorator('Form')->setElement($this->form)->render(false);
		//echo $this->form->SetLabel('Username Testing');
	
?>  
        <h2>New Password :</h2>
       <?php echo $this->form->getElement('newpassword');?>
        <div id="perror" style="color:red;height:20px;font-size:14px;width:500px;"></div>
        
        <h2>Confirm Password :</h2>
       <?php echo $this->form->getElement('cnewpassword');?>
        <div id="perror" style="color:red;height:20px;font-size:14px;width:500px;"></div>
       
       
       <div class="clr" style="height:2px;"></div>
      <?php 
	  			 $this->form->submit->setLabel('change');
	 			 echo $this->form->getElement('submit');
	  ?>
      
    <!-- </form>-->
     </div>
</div>