<div class="box1">
        <div class="wrapper">
          <article class="col1">
            <div class="pad_left1">
              <h2 class="pad_bot1"><cufon class="cufon cufon-canvas" alt="Basic " style="width: 87px; height: 32px;"><canvas width="112" height="39" style="width: 112px; height: 39px; top: -6px; left: -1px;"></canvas><cufontext>Basic </cufontext></cufon><cufon class="cufon cufon-canvas" alt="Courses" style="width: 123px; height: 32px;"><canvas width="141" height="39" style="width: 141px; height: 39px; top: -6px; left: -1px;"></canvas><cufontext>Courses</cufontext></cufon></h2>
            </div>
            <div class="wrapper pad_bot1">
              <figure class="left marg_right1"><img alt="" src="images/page2_img1.jpg"></figure>
              <p class="pad_bot1 pad_top2"><strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</strong></p>
              <p> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur sint occaecat.</p>
            </div>
            <div class="pad_left1">
              <div class="box2">
                <div class="wrapper">
                  <div class="cols">
                    <ul class="list3">
                      <li><a href="#">Sed ut perspiiatis unde omnis iste</a></li>
                      <li><a href="#">Natus error sit volupatem accusantiu</a></li>
                      <li><a href="#">Doloremque laudatium, totam rem</a></li>
                      <li><a href="#">Aperiam, eaqueipsa quae ahillo</a></li>
                    </ul>
                  </div>
                  <div class="cols pad_left2">
                    <ul class="list3">
                      <li><a href="#">Nemo enim ipsam volptatem quia</a></li>
                      <li><a href="#">Voluptas sit aspernatur aut odit autgit</a></li>
                      <li><a href="#">Sed quia consequuntur magni</a></li>
                      <li><a href="#">Dolores eos qui ratione voluptatem</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <p><strong>At vero eos et accusamus et iusto odio</strong> dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupidi- tate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fugat harum quidem rerum facilis est et expedita distinctio. </p>
            </div>
            <a class="button" href="#"><span><span>Read More</span></span></a> </article>
          <article class="col2 pad_left2">
            <div class="pad_left1">
              <h2><cufon class="cufon cufon-canvas" alt="Special " style="width: 118px; height: 32px;"><canvas width="143" height="39" style="width: 143px; height: 39px; top: -6px; left: -1px;"></canvas><cufontext>Special </cufontext></cufon><cufon class="cufon cufon-canvas" alt="Courses" style="width: 123px; height: 32px;"><canvas width="141" height="39" style="width: 141px; height: 39px; top: -6px; left: -1px;"></canvas><cufontext>Courses</cufontext></cufon></h2>
            </div>
            <ul class="list1 pad_bot1">
              <li><a href="#">At vero eos et accusamus</a></li>
              <li><a href="#">Dignissimos ducimus</a></li>
              <li><a href="#">Blanditiis praesentium volupta</a></li>
              <li><a href="#">Deleniti atque corrupti quos </a></li>
            </ul>
            <a class="button" href="#"><span><span>Read More</span></span></a>
            <div class="pad_left1">
              <h2 class="marg_top1"><cufon class="cufon cufon-canvas" alt="Evening " style="width: 132px; height: 32px;"><canvas width="158" height="39" style="width: 158px; height: 39px; top: -6px; left: -1px;"></canvas><cufontext>Evening </cufontext></cufon><cufon class="cufon cufon-canvas" alt="Courses" style="width: 123px; height: 32px;"><canvas width="141" height="39" style="width: 141px; height: 39px; top: -6px; left: -1px;"></canvas><cufontext>Courses</cufontext></cufon></h2>
              <p><strong>Nemo ipsam voluptatem</strong><br>
                Quia voluptas sit aspernatur aut odit aut fugit, seduia consequuntur magni dolores eos qui ratione. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non.<br>
                numquam eius modi tempora incidunt ut labore et dolore magnam.</p>
            </div>
            <a class="button" href="#"><span><span>Read More</span></span></a> </article>
        </div>
      </div>