<!DOCTYPE html>
<html lang="en">
<head>
<title>Learn Center | Admissions</title>
<meta charset="utf-8">

<?php echo $this->headLink()->appendStylesheet($this->baseUrl("css/reset.css")); ?> 
<?php echo $this->headLink()->appendStylesheet($this->baseUrl("css/layout.css")); ?> 
<?php echo $this->headLink()->appendStylesheet($this->baseUrl("css/style.css")); ?> 
<?php echo $this->headLink()->appendStylesheet($this->baseUrl("css/newwin.css")); ?>
<?php //echo $this->headLink()->appendStylesheet($this->baseUrl("css/stylemessage.css")); ?>
<?php //echo $this->headLink()->appendStylesheet($this->baseUrl("css/jquery.fancybox.css")); ?>


<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.fancybox.js?v=2.0.6"></script> 
                                    											
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery-1.5.2.js" ></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/cufon-yui.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/cufon-replace.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/Molengo_400.font.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/Expletus_Sans_400.font.js"></script>
<script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl();?>/js/newwin.js"></script>
<script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl();?>/js/newwin1.js"></script>
<!--[if lt IE 9]>
<script type="text/javascript" src="js/html5.js"></script>
<style type="text/css">.bg, .box2{behavior:url("js/PIE.htc");}</style>
<![endif]-->
</head>
<body id="page5">
<div class="body1">
  <div class="main">
    <!-- header -->
    <header>
      <div class="wrapper">
       <?php  $sess = new Zend_Session_Namespace('MyNamespace');
	  
		//echo "<pre>";
		 //print_r($sess->logindata);
		if(!empty($sess->logindata)){
		foreach($sess->logindata as $value){
				
				$id = $value->id;
				$username = $value->username;
			}
		}
		 ?>
        <nav>
        
        <?php 
		if(!empty($sess->logindata)){
		if($id!='')
					{?>
          <ul id="menu">
            <li><a href="<?php echo $this->baseUrl('auth/home');?>"><img height="50" width="50" src="<?php echo $this->baseUrl('images/home.png');?> "></a></li>
            <li><a href="<?php echo $this->baseUrl('social/friendrequest');?>">
           		 <img height="50" width="50" src="<?php echo $this->baseUrl('images/friendrequest.png');?> ">
				 
           		 <?php
			 		$count = $this->header();
					$countmessage = $count['countmessage'];
					$countrequest = $count['countrequest'];
					if($countrequest == 0){
					}
					else{
				?>
                	<div 
                    style="color: #FFF; text-align:center;  width:25px; height:36px; background-color:#F00; float:right; border-radius:100px; margin:-10px;  "> <?php echo $countrequest;?>
                    </div>
               <?php }}?>
            </a>
            
            </li>
          
          	  <li><a href="<?php echo $this->baseUrl('social/messagelist');?>">
           		 <img height="44" width="50" src="<?php echo $this->baseUrl('images/message.png');?> ">
				 
           		 <?php
			 		
				/*	if($count == 0){
					}
					else{*/
				?>
                 <?php if($countmessage == 0){}else{?>
                	<div 
                    style="color: #FFF; text-align:center;  width:25px; height:36px; background-color:#F00; float:right; border-radius:100px; margin:-10px;"><?php echo $countmessage?>
                    </div>
               <?php }?>
            </a>
            
            </li>
          
          </ul>
          <?php }else{?>
          <ul id="menu">
            <li><a href="<?php echo $this->baseUrl('auth');?>">Home</a></li>
          </ul>
          <?php }?>
        </nav>
       
        <?php if(@$id=='')
					{?>
        <ul id="icons">
                  <li><a class="thickbox" href="<?php echo $this->baseUrl('auth/login');?>?&amp;KeepThis=true&amp;TB_iframe=true&amp;height=350&amp;width=400" id="auth">Log In&nbsp;&nbsp;|</a></li>
                  <li><a class="thickbox" id='auth' href="<?php echo $this->baseUrl('auth/register');?>?&amp;KeepThis=true&amp;TB_iframe=true&amp;height=500&amp;width=400">Register</a></li>
        </ul>
        <?php }else{?>
         <ul id="icons">
                  <li><a href="#"id="auth"><?php 
				 // print_r($username);
        			echo $username 
					?>&nbsp;&nbsp;|</a></li>
                  <li><a id='auth' href="<?php echo $this->baseUrl('auth/logout');?>">Logout</a></li>
        </ul>
        <?php }?>
      </div>
<!--      <div class="wrapper">
        <h1><a href="index.html" id="logo">Learn Center</a></h1>
      </div>
      <div id="slogan"> We Will Open The World<span>of knowledge for you!</span> </div>
-->    </header>
    <!-- / header -->
  </div>
</div>
<div class="body2">
	
  <div class="main">
    <!-- content -->
    
    <div class="box1">
        <div class="wrapper">
        <?php
			$test = "success";
		 if(!empty($this->layout()->sendmessage[0]['msgsuccess']))
		{?>
        <script type='text/javascript'>alert("<?php echo $this->layout()->sendmessage[0]['msgsuccess']?>")</script>
        <?php }?>
    	<?php echo $this->layout()->content; ?>
        <?php 
				//$alluserdata=$this->layout()->alluser; 
				//$friendrequest=$this->layout()->friendrequest; 
		?>
        
        <?php 
		if($id!=''){
			//echo $this->layout()->sendmessage['msgsuccess'];
			echo $this->partial('sidebar.phtml',array(
												 'id'=>$id));
		}
		
		 ?>
        
      	 </div>
       </div>
    <!-- content -->
    <!-- footer -->
    <footer>
      <div class="wrapper">
        <div class="pad1">
          <div class="pad_left1">
            <div class="wrapper">
              <article class="col_1">
                <h3>Address:</h3>
                <p class="col_address"><strong>Country:<br>
                  City:<br>
                  Address:<br>
                  Email:</strong></p>
                <p>USA<br>
                  San Diego<br>
                  Beach st. 54<br>
                  <a href="#">lcenter@mail.com</a></p>
              </article>
              <article class="col_2 pad_left2">
                <h3>Join In:</h3>
                <ul class="list2">
                  <li><a href="#">Sign Up</a></li>
                  <li><a href="#">Forums</a></li>
                  <li><a href="#">Promotions</a></li>
                  <li><a href="#">Lorem</a></li>
                </ul>
              </article>
              <article class="col_3 pad_left2">
                <h3>Why Us:</h3>
                <ul class="list2">
                  <li><a href="#">Lorem ipsum dolor </a></li>
                  <li><a href="#">Aonsect adipisic</a></li>
                  <li><a href="#">Eiusmjkod tempor </a></li>
                  <li><a href="#">Incididunt ut labore </a></li>
                </ul>
              </article>
              <article class="col_4 pad_left2">
                <h3>Newsletter:</h3>
                <form id="newsletter" action="#" method="post">
                  <div class="wrapper">
                    <div class="bg">
                      <input type="text">
                    </div>
                  </div>
                  <a href="#" class="button"><span><span><strong>Subscribe</strong></span></span></a>
                </form>
              </article>
            </div>
            <div class="wrapper">
              <article class="call"> <span class="call1">Call Us Now: </span><span class="call2">1-800-567-8934</span> </article>
              <article class="col_4 pad_left2">Copyright &copy; <a href="#">Domain Name</a> All Rights Reserved<br>
                Design by <a target="_blank" href="http://www.templatemonster.com/">TemplateMonster.com</a></article>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- / footer -->
  </div>
  
</div>
<script type="text/javascript">Cufon.now();</script>
<div align=center>This template  downloaded form <a href='http://all-free-download.com/free-website-templates/'>free website templates</a></div></body>
</html>