<style>
	.clr{ clear:both;}

.user_cont{ width:452px; height:auto; float:left; margin:20px 0 0 20px;}

.user_cont h2{ font-family:Arial, Helvetica, sans-serif; font-size:15px; font-weight:bold; color:#3c3c3c; float:left; margin:0px; padding:0px; width:195px; text-transform:none;}

.user_cont. h1{ font-family:Arial, Helvetica, sans-serif; font-size:15px; font-weight:bold; color:#3c3c3c; float:left; margin:0px; padding:0px; width:500px; text-transform:none;}

.required { font-family:Arial, Helvetica, sans-serif; font-size:15px; font-weight:bold; color:#3c3c3c; float:left; margin:0px; padding:0px; width:500px; text-transform:none;}

.user_cont h3{ font-family:Arial, Helvetica, sans-serif; font-size:14px; font-weight:bold; color:#3c3c3c; float:left; margin:0px; padding:0px; width:500px;text-transform:none;}


.user_input{ width:250px; height:auto; float:left; border:solid 1px #d2d2d2; padding:5px;}

.user_text{ font-family:Arial, Helvetica, sans-serif; font-size:15px; font-weight:bold; color:#3c3c3c;}
.user_submit{ font-family:Arial, Helvetica, sans-serif; font-size:17px; font-weight:bold; color:#3c3c3c;}
.user_textarea{   border-color:#CCC;
    color: #3C3C3C;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 15px;
    font-weight: bold;
    height: 160px;
    width: 327px; }
#showpassword {
    display: none;
}
/* Login Css */
.frdreq{ color:#F00;}
li{ list-style-type:none; color: red}
</style>

<?php 
echo $this->form;

?>