<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery-1.5.2.js" ></script>
<script>
	$(document).ready(function(){
		$('input[name=email]').blur(function(){
				var email=$('input[name=email]').val();
				//alert(email);
				$.get('<?php echo $this->baseUrl('auth/checkuser');?>',{email:email},function(result){
						$('#emailerror').html(result);
					});
			});
		$('input[name=username]').blur(function(){
				var username=$('input[name=username]').val();
				//alert(email);
				$.get('<?php echo $this->baseUrl('auth/checkusername');?>',{username:username},function(result){
						$('#usererror').html(result);
					});
			});
		});
</script>
<style>
.clr{ clear:both;}

.user_cont{ width:452px; height:auto; float:left; margin:20px 0 0 20px;}

.user_cont h2{ font-family:Arial, Helvetica, sans-serif; font-size:15px; font-weight:bold; color:#3c3c3c; float:left; margin:0px; padding:0px; width:195px; text-transform:none;}

.user_cont. h1{ font-family:Arial, Helvetica, sans-serif; font-size:15px; font-weight:bold; color:#3c3c3c; float:left; margin:0px; padding:0px; width:500px; text-transform:none;}

.required { font-family:Arial, Helvetica, sans-serif; font-size:15px; font-weight:bold; color:#3c3c3c; float:left; margin:0px; padding:0px; width:500px; text-transform:none;}

.user_cont h3{ font-family:Arial, Helvetica, sans-serif; font-size:14px; font-weight:bold; color:#3c3c3c; float:left; margin:0px; padding:0px; width:500px;text-transform:none;}


.user_input{ width:250px; height:auto; float:left; border:solid 1px #d2d2d2; padding:5px;}

.user_text{ font-family:Arial, Helvetica, sans-serif; font-size:15px; font-weight:bold; color:#3c3c3c;}
.user_submit{ font-family:Arial, Helvetica, sans-serif; font-size:17px; font-weight:bold; color:#3c3c3c; margin: 40px 0 0 -74px;}
#showpassword {
    display: none;
}

.errors{color:red;font-size:16px; list-style:none;margin-left:-40px;}
</style>

<div class="user_cont">
<div id="cperror" style="color:red;height:20px;font-size:14px;width:500px;"><?php  echo $this->message['errorsuccess'];?></div>
<?php 

		$this->form->setAction($this->url());
		echo $this->form->getDecorator('Form')->setElement($this->form)->render(false);
		//echo $this->form->SetLabel('Username Testing');
	
?>
        <h2>Email Address:</h2>
        <?php echo $this->form->getElement('email');?>
                    <div  id="emailerror" style="color:red;height:20px;font-size:14px;margin-left: 194px;
    width: 250px;"></div>
    
        <div class="clr" style="height:10px;"></div>
        <h2>User Name :</h2>
       <?php echo $this->form->getElement('username');?>
                     <div id="usererror" style="color:red;height:20px;font-size:14px;margin-left: 194px;
    width: 250px;"></div>
 
        <div class="clr" style="height:10px;"></div>
        <h2>Password :</h2>
       <?php echo $this->form->getElement('password');?>
        <div id="perror" style="color:red;height:20px;font-size:14px;width:500px;"></div>
        
        <div class="clr" style="height:10px;"></div>
        <h2>Confirm Password :</h2>
        <?php echo $this->form->getElement('cpassword');?>
        <div id="cperror" style="color:red;height:20px;font-size:14px;width:500px;"></div>
    
        <div class="clr" style="height:10px;"></div>
        <h2>I am a :</h2>
      <?php echo $this->form->getElement('gender');?>
        
        <!--<div class="clr" style="height:20px;"></div>
        <h2>From :</h2>
        
        <select class="user_input" name="country" id="country"  onclick="return change_val()">
                    		<option value="">--Country--</option>
                          
                   			 </select>
        <div class="clr" style="height:20px;"></div>
        <h2>&nbsp;</h2>
       <select class="user_input" name="state" id="state" onFocus="return change_val()">
                    		<option value="">--State--</option>
                          
                                                 
                   			 </select>
       <div class="clr" style="height:20px;"></div>
       <h2>&nbsp;</h2>
        <select class="user_input"  name="city" id="city"  onFocus="return change_val()">
                    		<option value="">--City--</option>
                
                           
                            
                   		  </select>
       
       <div class="clr" style="height:20px;"></div>
       <center><div><?php //echo form_error('recaptcha_response_field'); ?>
                  <?php //echo $recaptcha; ?></div></center>
       
       <div class="clr" style="height:20px;"></div>
       <h3>-I agree to the Terms of Use and Privacy Policy</h3>-->
       
       <div class="clr" style="height:2px;"></div>
      <center><?php 
	  			$this->form->submit->setLabel('Sign Up');
	 			 echo $this->form->getElement('submit');?></center>
      
    <!-- </form>-->
     </div>